<?php

/**
 * ndPortfolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ndPortfolioTable extends PluginndPortfolioTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ndPortfolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ndPortfolio');
    }
}