<?php

/**
 * mediaObjectPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mediaObjectPictureTable extends PluginmediaObjectPictureTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mediaObjectPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mediaObjectPicture');
    }
}