<?php

/**
 * mediaObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    eie
 * @subpackage model
 * @author     Dachez Nicolas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mediaObject extends PluginmediaObject
{
}
