<?php

/**
 * mediaObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mediaObjectTable extends PluginmediaObjectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mediaObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mediaObject');
    }
}