<?php

/**
 * mediaAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mediaAlbumTable extends PluginmediaAlbumTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mediaAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mediaAlbum');
    }
}