<?php

/**
 * mediaAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mh
 * @subpackage model
 * @author     DACHEZ Nicolas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mediaAlbum extends PluginmediaAlbum
{
}
