<?php

/**
 * mediaObjectVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mediaObjectVideoTable extends PluginmediaObjectVideoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object mediaObjectVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mediaObjectVideo');
    }
}