<?php

/**
 * ndCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ndCategoriesTable extends PluginndCategoriesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ndCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ndCategories');
    }
}