<?php

/**
 * ndBannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ndBannerTable extends PluginndBannerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ndBannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ndBanner');
    }
}