<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('nd_banner_translation', 'nd_banner_translation_id_nd_banner_id', array(
             'name' => 'nd_banner_translation_id_nd_banner_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'nd_banner',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('nd_banner_translation', 'nd_banner_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('nd_banner_translation', 'nd_banner_translation_id_nd_banner_id');
        $this->removeIndex('nd_banner_translation', 'nd_banner_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}