peanutSettings:
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    value:
      type: clob
      notnull: true

peanutMenu:
  actAs:
    I18n:
      fields: [name]
      actAs:
        Sluggable:
          fields: [name]
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    name:
      type: string(255)
      notnull: true